# lyne help - Show available commands

echo "lyne - Dotfiles management CLI"
echo ""
echo "Usage: lyne <command> [args...]"
echo ""
echo "Commands:"
echo "  state       Manage state.json"
echo "  migrate     Manage migration scripts"
echo "  update      Pull latest changes, sync state and run migrations"
echo "  git         Run git commands in the dotfiles repo"
echo "  reload      Reload QuickShell"
echo "  help        Show this help message"
echo ""
echo "Run 'lyne <command> --help' for more information on a command."
